"""Agent domain models."""

from __future__ import annotations

from pydantic import BaseModel, Field


class AgentCreate(BaseModel):
    """Input model for creating an agent."""

    name: str = Field(min_length=1, max_length=100)
    personality: str = Field(min_length=1, max_length=1000)
    description: str | None = Field(default=None, max_length=500)


class AgentGenerate(BaseModel):
    """Input for AI-powered agent generation."""

    keywords: str = Field(min_length=1)


class AgentGenerationResponse(BaseModel):
    """Full agent profile generated by AI."""

    name: str
    personality: str
    description: str


class AgentResponse(BaseModel):
    """Output model for agent data."""

    id: str
    name: str
    personality: str
    description: str | None = None
    avatar_url: str | None = None


class IntegrationInfo(BaseModel):
    """Available integration metadata."""

    type: str
    display_name: str
    description: str


class CapabilityInfo(BaseModel):
    """Available capability metadata."""

    id: str
    name: str
    description: str
