"""Agent domain models and database entities."""

from __future__ import annotations

from datetime import UTC, datetime
from uuid import UUID, uuid4

from sqlmodel import JSON, Column, Field, SQLModel


class AgentBase(SQLModel):
    """Shared fields for Agent models."""

    name: str = Field(index=True, max_length=100)
    personality: str = Field(max_length=1000)
    description: str | None = Field(default=None, max_length=500)
    avatar_url: str | None = Field(default=None)
    system_prompt: str | None = Field(default=None)
    status: str = Field(default="active")
    mood: str = Field(default="Neutral")


class Agent(AgentBase, table=True):
    """Database entity for Agents."""

    __tablename__ = "agents"

    id: UUID = Field(default_factory=uuid4, primary_key=True)
    user_id: UUID = Field(index=True)

    # Store complex lists as JSONB
    goals: list[str] = Field(default=[], sa_column=Column(JSON))
    capabilities: list[str] = Field(default=[], sa_column=Column(JSON))
    integrations: list[str] = Field(default=[], sa_column=Column(JSON))
    integration_configs: dict = Field(default_factory=dict, sa_column=Column(JSON))

    message_count: int = Field(default=0)
    created_at: datetime = Field(default_factory=lambda: datetime.now(UTC))


class AgentCreate(AgentBase):
    """Schema for creating a new agent."""

    goals: list[str] = []
    capabilities: list[str] = []
    integrations: list[str] = []
    integration_configs: dict = Field(default_factory=dict)


class AgentResponse(AgentBase):
    """Schema for returning agent data."""

    id: UUID
    goals: list[str]
    capabilities: list[str]
    integrations: list[str]
    integration_configs: dict
    message_count: int
    created_at: datetime


class AgentGenerate(SQLModel):
    """Input for AI-powered agent generation."""

    keywords: str


class AgentGenerationResponse(SQLModel):
    """Full agent profile generated by AI."""

    name: str
    personality: str
    description: str
    goals: list[str]
