"""Agent domain Pydantic schemas."""

from __future__ import annotations

from datetime import datetime
from typing import Any
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field, field_validator


class CapabilityResponse(BaseModel):
    """Schema for returning capability data.

    Attributes:
        id: Unique identifier for the capability.
        name: Name of the capability.
        description: Description of the capability.
        icon: Icon representing the capability.
        status: Current status of the capability.
        created_at: The timestamp when the capability was created.
    """

    id: str
    name: str
    description: str
    icon: str
    status: str
    created_at: datetime


class IntegrationResponse(BaseModel):
    """Schema for returning integration data.

    Attributes:
        id: Unique identifier for the integration.
        display_name: Display name of the integration.
        description: Description of the integration.
        icon: Icon representing the integration.
        status: Current status of the integration.
        config_schema: Schema for the integration configuration.
        created_at: The timestamp when the integration was created.
    """

    id: str
    display_name: str
    description: str
    icon: str
    status: str
    config_schema: list | dict
    created_at: datetime


class AgentBase(BaseModel):
    """Shared fields for Agent schemas."""

    name: str = Field(max_length=100)
    personality: str = Field(max_length=1000)
    description: str | None = Field(default=None, max_length=500)
    system_prompt: str | None = Field(default=None)
    status: str = Field(default="active")
    mood: str = Field(default="Neutral")


class AgentCreate(AgentBase):
    """Schema for creating a new agent."""

    goals: list[str] = Field(default_factory=list)
    capabilities: list[str] = Field(default_factory=list)
    integrations: list[str] = Field(default_factory=list)
    integration_configs: dict = Field(default_factory=dict)


class AgentResponse(AgentBase):
    """Schema for returning agent data."""

    model_config = ConfigDict(from_attributes=True)

    id: UUID
    goals: list[str] = Field(default_factory=list)
    capabilities: list[str] = Field(default_factory=list)
    integrations: list[str] = Field(default_factory=list)
    integration_configs: dict = Field(default_factory=dict)
    message_count: int
    created_at: datetime
    updated_at: datetime

    @field_validator("capabilities", mode="before")
    @classmethod
    def extract_capabilities(cls, v: Any) -> list[str]:
        """Extract capability IDs from a prefetched Tortoise M2M relation or plain list."""
        if hasattr(v, "related_objects"):
            return [obj.pk for obj in v.related_objects]
        return list(v) if v else []

    @field_validator("integrations", mode="before")
    @classmethod
    def extract_integrations(cls, v: Any) -> list[str]:
        """Extract integration IDs from prefetched agent_integrations or plain list."""
        if hasattr(v, "related_objects"):
            return [
                obj.integration_id if hasattr(obj, "integration_id") else obj.pk
                for obj in v.related_objects
                if getattr(obj, "enabled", True)
            ]
        if hasattr(v, "__iter__") and not isinstance(v, (str, dict)):
            items = list(v)
            if items and hasattr(items[0], "integration_id"):
                return [item.integration_id for item in items if item.enabled]
            return [str(item) for item in items]
        return list(v) if v else []


class AgentTemplateResponse(BaseModel):
    """Schema for returning agent template data."""

    model_config = ConfigDict(from_attributes=True)

    id: UUID
    name: str
    description: str
    personality: str
    goals: list[str] = Field(default_factory=list)
    created_at: datetime


class AgentUpdate(BaseModel):
    """Schema for updating an existing agent."""

    name: str | None = Field(default=None, max_length=100)
    personality: str | None = Field(default=None, max_length=1000)
    description: str | None = Field(default=None, max_length=500)
    goals: list[str] | None = None
    capabilities: list[str] | None = None
    integrations: list[str] | None = None
    integration_configs: dict[str, Any] | None = None


class AgentGenerate(BaseModel):
    """Input for AI-powered agent generation."""

    keywords: str


class AgentGenerationResponse(BaseModel):
    """Full agent profile generated by AI."""

    name: str
    personality: str
    description: str
    capabilities: list[str] = Field(
        default_factory=list,
        description="List of capability IDs (e.g., web_search, memory) the agent should have.",
    )
    suggested_integrations: list[str] = Field(
        default_factory=list,
        description="List of integration IDs (e.g., discord, slack) the agent could use.",
    )
    goals: list[str]


class MoodResponse(BaseModel):
    """Structured output for mood classification."""

    mood: str
