/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./app/**/*.{js,jsx,ts,tsx}', './src/**/*.{js,jsx,ts,tsx}'],
  presets: [require('nativewind/preset')],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: '#2563EB',
          light: '#60A5FA',
          dark: '#1E40AF',
          surface: '#1E293B',
          surfaceLight: '#EFF6FF',
        },
        background: {
          dark: '#0F0F14',
          light: '#F8F8FC',
        },
        surface: {
          dark: '#1A1A22',
          highDark: '#242430',
          highestDark: '#2E2E3C',
          light: '#FFFFFF',
          highLight: '#F0F0F6',
          highestLight: '#E8E8F0',
        },
        border: {
          dark: '#3A3A4A',
          light: '#D8D8E4',
        },
        onSurface: {
          dark: '#F0EFF4',
          mutedDark: '#A0A0B0',
          disabledDark: '#606070',
          light: '#12121A',
          mutedLight: '#6E6E80',
          disabledLight: '#B0B0C0',
        },
        status: {
          success: '#34D399',
          successSurfaceDark: '#0D2E1F',
          successSurfaceLight: '#F0FDF4',
          warning: '#FBBF24',
          warningSurfaceDark: '#2E2610',
          warningSurfaceLight: '#FFFBEB',
          error: '#F87171',
          errorSurfaceDark: '#2E1212',
          errorSurfaceLight: '#FEF2F2',
          info: '#60A5FA',
          infoSurfaceDark: '#121E2E',
          infoSurfaceLight: '#EFF6FF',
        },
      },
      spacing: {
        none: '0px',
        xxs: '2px',
        xs: '4px',
        sm: '8px',
        md: '12px',
        lg: '16px',
        xl: '20px',
        xxl: '24px',
        xxxl: '32px',
        huge: '40px',
        massive: '48px',
        colossal: '64px',
      },
      borderRadius: {
        none: '0px',
        xs: '4px',
        sm: '8px',
        md: '12px',
        lg: '16px',
        xl: '20px',
        xxl: '24px',
        full: '9999px',
      },
    },
  },
  plugins: [],
};
