import 'dart:convert';

/// Data model for a single chat message.
///
/// Each message has a unique [id], a [timestamp], a [status] reflecting
/// its delivery state, and optional [crewTaskType] for CrewAI responses.
class ChatMessage {
  final String id;
  final String text;
  final bool isUser;
  final DateTime timestamp;
  final MessageStatus status;

  /// Set for assistant messages generated by a CrewAI crew.
  final String? crewTaskType;

  const ChatMessage({
    required this.id,
    required this.text,
    required this.isUser,
    required this.timestamp,
    this.status = MessageStatus.sent,
    this.crewTaskType,
  });

  /// Creates a user message with auto-generated ID and current timestamp.
  factory ChatMessage.user(String text) => ChatMessage(
        id: _generateId(),
        text: text,
        isUser: true,
        timestamp: DateTime.now(),
        status: MessageStatus.sent,
      );

  /// Creates an assistant placeholder (empty text triggers typing indicator).
  factory ChatMessage.assistantPlaceholder() => ChatMessage(
        id: _generateId(),
        text: '',
        isUser: false,
        timestamp: DateTime.now(),
        status: MessageStatus.streaming,
      );

  ChatMessage copyWith({
    String? text,
    MessageStatus? status,
    String? crewTaskType,
  }) =>
      ChatMessage(
        id: id,
        text: text ?? this.text,
        isUser: isUser,
        timestamp: timestamp,
        status: status ?? this.status,
        crewTaskType: crewTaskType ?? this.crewTaskType,
      );

  // ---------------------------------------------------------------------------
  // Serialization
  // ---------------------------------------------------------------------------

  Map<String, dynamic> toJson() => {
        'id': id,
        'text': text,
        'isUser': isUser,
        'timestamp': timestamp.toIso8601String(),
        'status': status.name,
        'crewTaskType': crewTaskType,
      };

  factory ChatMessage.fromJson(Map<String, dynamic> json) => ChatMessage(
        id: json['id'] as String,
        text: json['text'] as String,
        isUser: json['isUser'] as bool,
        timestamp: DateTime.parse(json['timestamp'] as String),
        status: MessageStatus.values.byName(json['status'] as String),
        crewTaskType: json['crewTaskType'] as String?,
      );

  /// Encode a list of messages to a JSON string.
  static String encodeList(List<ChatMessage> messages) =>
      jsonEncode(messages.map((m) => m.toJson()).toList());

  /// Decode a JSON string to a list of messages.
  static List<ChatMessage> decodeList(String jsonString) {
    final list = jsonDecode(jsonString) as List<dynamic>;
    return list.cast<Map<String, dynamic>>().map(ChatMessage.fromJson).toList();
  }

  // ---------------------------------------------------------------------------
  // ID generation
  // ---------------------------------------------------------------------------

  static int _counter = 0;

  static String _generateId() {
    _counter++;
    return '${DateTime.now().millisecondsSinceEpoch}_$_counter';
  }
}

/// The delivery/processing status of a [ChatMessage].
enum MessageStatus {
  /// Message is being sent to the server.
  sending,

  /// Message has been sent and acknowledged.
  sent,

  /// Assistant response is actively streaming.
  streaming,

  /// Message delivery or generation failed.
  failed,
}
