import re

with open("frontend/lib/models/chat_message.dart", "w") as f:
    f.write("""import 'dart:convert';
import 'message_status.dart';

/// Data model for a single chat message.
///
/// Each message has a unique [id], a [timestamp], a [status] reflecting
/// its delivery state, and optional [crewTaskType] for CrewAI responses.
class ChatMessage {
  final String id;
  final String roomId;
  final String? userId;
  final String? agentId;
  final String text;
  final DateTime timestamp;
  final MessageStatus status;

  /// Set for assistant messages generated by a CrewAI crew.
  final String? crewTaskType;

  const ChatMessage({
    required this.id,
    this.roomId = 'temp',
    this.userId,
    this.agentId,
    required this.text,
    required this.timestamp,
    this.status = MessageStatus.sent,
    this.crewTaskType,
  });

  bool get isUser => userId != null;
  bool get isAgent => agentId != null;

  /// Creates a user message with auto-generated ID and current timestamp.
  factory ChatMessage.user(String text) => ChatMessage(
        id: _generateId(),
        text: text,
        userId: 'temp',
        timestamp: DateTime.now(),
        status: MessageStatus.sent,
      );

  /// Creates an assistant placeholder (empty text triggers typing indicator).
  factory ChatMessage.assistantPlaceholder() => ChatMessage(
        id: _generateId(),
        text: '',
        agentId: 'temp',
        timestamp: DateTime.now(),
        status: MessageStatus.streaming,
      );

  ChatMessage copyWith({
    String? id,
    String? roomId,
    String? userId,
    String? agentId,
    String? text,
    DateTime? timestamp,
    MessageStatus? status,
    String? crewTaskType,
  }) =>
      ChatMessage(
        id: id ?? this.id,
        roomId: roomId ?? this.roomId,
        userId: userId ?? this.userId,
        agentId: agentId ?? this.agentId,
        text: text ?? this.text,
        timestamp: timestamp ?? this.timestamp,
        status: status ?? this.status,
        crewTaskType: crewTaskType ?? this.crewTaskType,
      );

  // ---------------------------------------------------------------------------
  // Serialization
  // ---------------------------------------------------------------------------

  Map<String, dynamic> toJson() => {
        'id': id,
        'room_id': roomId,
        'user_id': userId,
        'agent_id': agentId,
        'content': text, // we map text to content for API
        'created_at': timestamp.toIso8601String(),
        'status': status.name,
        'crewTaskType': crewTaskType,
      };

  factory ChatMessage.fromJson(Map<String, dynamic> json) => ChatMessage(
        id: json['id'].toString(),
        roomId: (json['room_id'] ?? 'temp').toString(),
        userId: json['user_id']?.toString() ?? (json['isUser'] == true ? 'temp' : null),
        agentId: json['agent_id']?.toString() ?? (json['isUser'] == false ? 'temp' : null),
        text: (json['content'] ?? json['text'] ?? '').toString(),
        timestamp: json['created_at'] != null ? DateTime.parse(json['created_at'].toString()) : (json['timestamp'] != null ? DateTime.parse(json['timestamp'].toString()) : DateTime.now()),
        status: json['status'] != null ? MessageStatus.values.byName(json['status'] as String) : MessageStatus.sent,
        crewTaskType: json['crewTaskType'] as String?,
      );

  /// Encode a list of messages to a JSON string.
  static String encodeList(List<ChatMessage> messages) =>
      jsonEncode(messages.map((m) => m.toJson()).toList());

  /// Decode a JSON string to a list of messages.
  static List<ChatMessage> decodeList(String jsonString) {
    final list = jsonDecode(jsonString) as List<dynamic>;
    return list.cast<Map<String, dynamic>>().map(ChatMessage.fromJson).toList();
  }

  // ---------------------------------------------------------------------------
  // ID generation
  // ---------------------------------------------------------------------------

  static int _counter = 0;

  static String _generateId() {
    _counter++;
    return '${DateTime.now().millisecondsSinceEpoch}_$_counter';
  }
}
""")
