from typing import Protocol
from uuid import UUID

from app.domain.agents.models import Agent, AgentTemplate, Capability, Integration


class IAgentRepository(Protocol):
    async def list_capabilities(self) -> list[Capability]: ...
    async def list_integrations(self) -> list[Integration]: ...
    async def get_by_id(self, agent_id: UUID | str) -> Agent | None: ...
    async def list_by_user(self, user_id: UUID | str) -> list[Agent]: ...
    async def list_templates(self, skip: int = 0, limit: int = 100) -> list[AgentTemplate]: ...
    async def create(self, agent: Agent) -> Agent: ...
    async def update_mood(self, agent_id: UUID | str, mood: str) -> None: ...
    async def update_agent(
        self, agent_id: UUID | str, user_id: UUID | str, **fields: object
    ) -> Agent | None: ...
    async def delete_agent(self, agent_id: UUID | str, user_id: UUID | str) -> bool: ...
    async def increment_message_count(self, agent_id: UUID | str) -> None: ...
    async def upsert_affinity(
        self, user_id: UUID, agent_id: UUID, score_delta: float = 1.0
    ) -> None: ...
