"""Agents and Chat Rooms logic for Miru."""

from __future__ import annotations

import asyncio
import json
import logging
from typing import TYPE_CHECKING, Any, cast

if TYPE_CHECKING:
    from collections.abc import AsyncIterator
    from uuid import UUID

from crewai import Agent as CrewAgent
from crewai import Crew, Process, Task
from crewai_tools import TavilySearchTool
from pydantic import BaseModel, Field

from app.config import get_settings
from app.crew import make_llm
from app.database import get_supabase
from app.memory import retrieve_memories, store_memory
from app.openrouter import chat_completion, stream_chat

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Available integration types (registry for UI + validation)
# ---------------------------------------------------------------------------

AVAILABLE_INTEGRATIONS = [
    {
        "type": "spotify",
        "display_name": "Spotify",
        "description": "Play music, manage playlists, and get recommendations",
        "icon": "music_note",
        "status": "coming_soon",
    },
    {
        "type": "discord",
        "display_name": "Discord",
        "description": "Send messages, manage channels, and monitor servers",
        "icon": "forum",
        "status": "coming_soon",
    },
    {
        "type": "google_calendar",
        "display_name": "Google Calendar",
        "description": "Schedule events, check availability, and set reminders",
        "icon": "calendar_today",
        "status": "coming_soon",
    },
    {
        "type": "github",
        "display_name": "GitHub",
        "description": "Manage repos, review PRs, and track issues",
        "icon": "code",
        "status": "coming_soon",
    },
    {
        "type": "slack",
        "display_name": "Slack",
        "description": "Send messages, manage channels, and automate workflows",
        "icon": "tag",
        "status": "coming_soon",
    },
    {
        "type": "notion",
        "display_name": "Notion",
        "description": "Create pages, manage databases, and organize notes",
        "icon": "article",
        "status": "coming_soon",
    },
]

# Available built-in capabilities
AVAILABLE_CAPABILITIES = [
    {
        "id": "web_search",
        "name": "Web Search",
        "description": "Search the internet for real-time information",
        "icon": "search",
    },
    {
        "id": "code_execution",
        "name": "Code Execution",
        "description": "Write and run code snippets",
        "icon": "terminal",
    },
    {
        "id": "image_generation",
        "name": "Image Generation",
        "description": "Create images from text descriptions",
        "icon": "image",
    },
    {
        "id": "data_analysis",
        "name": "Data Analysis",
        "description": "Analyze data, create charts and insights",
        "icon": "analytics",
    },
    {
        "id": "file_management",
        "name": "File Management",
        "description": "Read, write, and organize files",
        "icon": "folder",
    },
    {
        "id": "memory_recall",
        "name": "Memory Recall",
        "description": "Remember past conversations and user preferences",
        "icon": "psychology",
    },
    {
        "id": "task_planning",
        "name": "Task Planning",
        "description": "Break down complex tasks and create action plans",
        "icon": "checklist",
    },
    {
        "id": "summarization",
        "name": "Summarization",
        "description": "Condense long texts into key points",
        "icon": "summarize",
    },
]


# ---------------------------------------------------------------------------
# Models
# ---------------------------------------------------------------------------


class AgentCreate(BaseModel):
    """Input model for creating an agent."""

    name: str = Field(min_length=1, max_length=100)
    personality: str = Field(min_length=1, max_length=1000)
    description: str | None = Field(default=None, max_length=500)
    goals: list[str] = Field(default_factory=list)
    capabilities: list[str] = Field(default_factory=list)
    integrations: list[str] = Field(default_factory=list)
    system_prompt: str | None = None


class AgentGenerate(BaseModel):
    """Input for AI-powered agent generation."""

    keywords: str = Field(min_length=1)


class AgentGenerationResponse(BaseModel):
    """Full agent profile generated by AI."""

    name: str
    personality: str
    description: str
    goals: list[str]
    capabilities: list[str]
    suggested_integrations: list[str]


class AgentResponse(BaseModel):
    """Output model for agent data."""

    id: str
    name: str
    personality: str
    description: str | None = None
    goals: list[str] = Field(default_factory=list)
    capabilities: list[str] = Field(default_factory=list)
    integrations: list[str] = Field(default_factory=list)
    system_prompt: str | None = None
    status: str = "active"
    created_at: str


class IntegrationInfo(BaseModel):
    """Available integration metadata."""

    type: str
    display_name: str
    description: str
    icon: str
    status: str


class CapabilityInfo(BaseModel):
    """Available capability metadata."""

    id: str
    name: str
    description: str
    icon: str


class RoomCreate(BaseModel):
    name: str


class RoomUpdate(BaseModel):
    name: str


class RoomResponse(BaseModel):
    id: str
    name: str
    created_at: str


class RoomAgentAdd(BaseModel):
    agent_id: str


class ChatMessageCreate(BaseModel):
    content: str


class ChatMessageResponse(BaseModel):
    id: str
    room_id: str
    user_id: str | None
    agent_id: str | None
    content: str
    created_at: str


# ---------------------------------------------------------------------------
# System prompt builder
# ---------------------------------------------------------------------------


def build_system_prompt(
    name: str,
    personality: str,
    description: str | None = None,
    goals: list[str] | None = None,
    capabilities: list[str] | None = None,
) -> str:
    """Build a rich system prompt from agent profile fields.

    Combines personality, goals, and capabilities into a structured prompt
    that gives the agent clear identity and purpose.
    """
    sections = [f"You are {name}."]

    if description:
        sections.append(description)

    sections.append(f"\nPersonality & Behavior:\n{personality}")

    if goals:
        goal_list = "\n".join(f"- {g}" for g in goals)
        sections.append(f"\nYour Goals:\n{goal_list}")

    if capabilities:
        cap_names = []
        cap_lookup = {c["id"]: c["name"] for c in AVAILABLE_CAPABILITIES}
        for cap_id in capabilities:
            cap_names.append(cap_lookup.get(cap_id, cap_id))
        cap_list = ", ".join(cap_names)
        sections.append(f"\nYou have the following capabilities: {cap_list}.")

    return "\n".join(sections)


# ---------------------------------------------------------------------------
# Database Operations
# ---------------------------------------------------------------------------


async def create_agent(agent_data: AgentCreate, user_id: UUID) -> AgentResponse:
    """Create a new agent with full profile."""
    supabase = get_supabase()

    # Build system prompt if not explicitly provided
    system_prompt = agent_data.system_prompt or build_system_prompt(
        name=agent_data.name,
        personality=agent_data.personality,
        description=agent_data.description,
        goals=agent_data.goals,
        capabilities=agent_data.capabilities,
    )

    insert_data: dict[str, Any] = {
        "user_id": str(user_id),
        "name": agent_data.name,
        "personality": agent_data.personality,
        "description": agent_data.description,
        "goals": agent_data.goals,
        "capabilities": agent_data.capabilities,
        "integrations": agent_data.integrations,
        "system_prompt": system_prompt,
    }

    response = supabase.table("agents").insert(insert_data).execute()
    data = cast("list[dict[str, Any]]", response.data)[0]
    return _agent_from_row(data)


async def get_agents(user_id: UUID) -> list[AgentResponse]:
    """List all agents for a user."""
    supabase = get_supabase()
    response = supabase.table("agents").select("*").eq("user_id", str(user_id)).execute()
    return [_agent_from_row(record) for record in cast("list[dict[str, Any]]", response.data)]


def _agent_from_row(data: dict[str, Any]) -> AgentResponse:
    """Convert a database row to an AgentResponse, handling JSONB fields."""
    goals = data.get("goals", [])
    if isinstance(goals, str):
        goals = json.loads(goals)

    capabilities = data.get("capabilities", [])
    if isinstance(capabilities, str):
        capabilities = json.loads(capabilities)

    integrations = data.get("integrations", [])
    if isinstance(integrations, str):
        integrations = json.loads(integrations)

    return AgentResponse(
        id=str(data["id"]),
        name=data["name"],
        personality=data["personality"],
        description=data.get("description"),
        goals=goals if goals else [],
        capabilities=capabilities if capabilities else [],
        integrations=integrations if integrations else [],
        system_prompt=data.get("system_prompt"),
        status=data.get("status", "active"),
        created_at=str(data["created_at"]),
    )


async def generate_agent(keywords: str) -> AgentGenerationResponse:
    """Generate a full agent profile from keywords using AI.

    Returns a rich profile including name, personality, description,
    goals, capabilities, and suggested integrations — all inferred
    from the user's keywords.
    """
    available_caps = [c["id"] for c in AVAILABLE_CAPABILITIES]
    available_integrations = [i["type"] for i in AVAILABLE_INTEGRATIONS]

    prompt = (
        f"Create a creative and unique AI agent/persona based on these keywords: {keywords}.\n\n"
        "Respond with a JSON object containing:\n"
        '- "name": A creative, memorable name for this agent\n'
        '- "personality": A concise system prompt (2-4 sentences) defining how '
        "this agent behaves, speaks, and thinks\n"
        '- "description": A one-sentence summary of what this agent does\n'
        '- "goals": An array of 2-4 specific goals this agent works towards '
        "(e.g. help user stay organized, provide creative inspiration)\n"
        '- "capabilities": An array of relevant capability IDs from this list: '
        f"{available_caps}\n"
        '- "suggested_integrations": An array of relevant integration types '
        f"from this list: {available_integrations}\n\n"
        "Only include capabilities and integrations that genuinely match the "
        "agent's purpose. Be creative with the name and personality.\n\n"
        "Example JSON:\n"
        "{\n"
        '  "name": "Maestro",\n'
        '  "personality": "You are a passionate music curator and DJ. You speak '
        "with enthusiasm about rhythms and melodies. You help users discover new "
        'music and create the perfect playlists for any mood.",\n'
        '  "description": "A music-obsessed curator who helps you discover and '
        'organize your perfect soundtrack",\n'
        '  "goals": ["Help discover new music matching user taste", '
        '"Create mood-based playlists", "Track listening habits and suggest '
        'improvements"],\n'
        '  "capabilities": ["web_search", "memory_recall"],\n'
        '  "suggested_integrations": ["spotify"]\n'
        "}"
    )

    messages = [
        {
            "role": "system",
            "content": (
                "You are a creative AI agent designer. You generate detailed, "
                "well-thought-out agent profiles as JSON. Always respond with "
                "valid JSON only — no markdown fences, no explanation."
            ),
        },
        {"role": "user", "content": prompt},
    ]

    response_text = await chat_completion(messages)

    cleaned_json = response_text.strip()
    if cleaned_json.startswith("```json"):
        cleaned_json = cleaned_json[7:]
    if cleaned_json.startswith("```"):
        cleaned_json = cleaned_json[3:]
    if cleaned_json.endswith("```"):
        cleaned_json = cleaned_json[:-3]
    cleaned_json = cleaned_json.strip()

    data = json.loads(cleaned_json)

    # Validate capabilities and integrations against known lists
    valid_caps = {c["id"] for c in AVAILABLE_CAPABILITIES}
    valid_integrations = {i["type"] for i in AVAILABLE_INTEGRATIONS}

    return AgentGenerationResponse(
        name=data["name"],
        personality=data["personality"],
        description=data.get("description", ""),
        goals=data.get("goals", []),
        capabilities=[c for c in data.get("capabilities", []) if c in valid_caps],
        suggested_integrations=[
            i for i in data.get("suggested_integrations", []) if i in valid_integrations
        ],
    )


def get_available_integrations() -> list[IntegrationInfo]:
    """Return the list of available integrations."""
    return [IntegrationInfo(**i) for i in AVAILABLE_INTEGRATIONS]


def get_available_capabilities() -> list[CapabilityInfo]:
    """Return the list of available capabilities."""
    return [CapabilityInfo(**c) for c in AVAILABLE_CAPABILITIES]


async def create_room(room_data: RoomCreate, user_id: UUID) -> RoomResponse:
    supabase = get_supabase()
    response = (
        supabase.table("chat_rooms")
        .insert({"user_id": str(user_id), "name": room_data.name})
        .execute()
    )
    data = cast("list[dict[str, Any]]", response.data)[0]
    return RoomResponse(**data)


async def get_rooms(user_id: UUID) -> list[RoomResponse]:
    supabase = get_supabase()
    response = supabase.table("chat_rooms").select("*").eq("user_id", str(user_id)).execute()
    return [RoomResponse(**record) for record in cast("list[dict[str, Any]]", response.data)]


async def update_room(room_id: str, room_data: RoomUpdate, user_id: UUID) -> RoomResponse:
    supabase = get_supabase()
    response = (
        supabase.table("chat_rooms")
        .update({"name": room_data.name})
        .eq("id", room_id)
        .eq("user_id", str(user_id))
        .execute()
    )
    if not response.data:
        from fastapi import HTTPException

        raise HTTPException(status_code=404, detail="Room not found or unauthorized")
    data = cast("list[dict[str, Any]]", response.data)[0]
    return RoomResponse(**data)


async def add_agent_to_room(room_id: str, agent_id: str, user_id: UUID) -> dict:
    supabase = get_supabase()
    supabase.table("chat_room_agents").insert({"room_id": room_id, "agent_id": agent_id}).execute()
    return {"status": "added"}


async def get_room_agents(room_id: str, user_id: UUID) -> list[AgentResponse]:
    supabase = get_supabase()
    response = (
        supabase.table("chat_room_agents").select("agents(*)").eq("room_id", room_id).execute()
    )
    agents_data = []
    for record in cast("list[dict[str, Any]]", response.data):
        if record.get("agents"):
            agents_data.append(_agent_from_row(record["agents"]))
    return agents_data


async def get_room_messages(room_id: str, user_id: UUID) -> list[ChatMessageResponse]:
    supabase = get_supabase()
    response = (
        supabase.table("chat_messages")
        .select("*")
        .eq("room_id", room_id)
        .order("created_at", desc=False)
        .execute()
    )
    return [ChatMessageResponse(**record) for record in cast("list[dict[str, Any]]", response.data)]


async def save_message(
    room_id: str, content: str, sender_id: str, is_agent: bool
) -> ChatMessageResponse:
    supabase = get_supabase()
    insert_data = {"room_id": room_id, "content": content}
    if is_agent:
        insert_data["agent_id"] = sender_id
    else:
        insert_data["user_id"] = sender_id

    response = supabase.table("chat_messages").insert(insert_data).execute()
    data = cast("list[dict[str, Any]]", response.data)[0]
    return ChatMessageResponse(**data)


# ---------------------------------------------------------------------------
# Orchestrator Logic
# ---------------------------------------------------------------------------


async def orchestrate_turn(history_text: str, room_agents: list[AgentResponse]) -> list[str]:
    """Ask an LLM to decide which agent(s) should speak next.

    Returns a list of agent IDs. Returns an empty list if it decides the agents
    should stop and wait for the user.
    """
    agents_info = "\n".join([f"- {a.name} (ID: {a.id}): {a.personality}" for a in room_agents])

    system_prompt = (
        "You are an Orchestrator managing a chat room with multiple AI personas and a User.\n"
        "Your job is to read the conversation history and decide who should speak next.\n\n"
        f"Available Agents:\n{agents_info}\n\n"
        "Rules:\n"
        "1. If the User's query is answered and the conversation has naturally concluded for this turn, return an empty list `[]` to wait for the User.\n"
        "2. If an Agent is directly addressed or uniquely qualified to answer, return their ID.\n"
        "3. If multiple agents should collaborate, you can return multiple IDs (they will speak sequentially).\n"
        "4. If an Agent just spoke and another Agent might want to add value, agree, or disagree based on their personality, return their ID.\n"
        '5. Respond ONLY with a valid JSON array of Agent IDs (strings). E.g. `["id1"]` or `["id1", "id2"]` or `[]`.'
    )

    messages = [
        {"role": "system", "content": system_prompt},
        {
            "role": "user",
            "content": f"Conversation history:\n{history_text}\n\nWho should speak next?",
        },
    ]

    try:
        response_text = await chat_completion(messages)
        cleaned = response_text.strip()
        if cleaned.startswith("```json"):
            cleaned = cleaned[7:]
        if cleaned.endswith("```"):
            cleaned = cleaned[:-3]

        selected_ids = json.loads(cleaned.strip())
        if not isinstance(selected_ids, list):
            logger.error(f"Orchestrator returned non-list: {selected_ids}")
            return []
        return [str(aid) for aid in selected_ids]
    except Exception as e:
        logger.error(f"Orchestrator failed: {e}")
        # Fallback: if orchestrator fails, let the first available agent speak, then stop.
        if room_agents:
            return [room_agents[0].id]
        return []


# ---------------------------------------------------------------------------
# Chat Logic
# ---------------------------------------------------------------------------


async def stream_room_responses(
    room_id: str, user_message: str, user_id: UUID
) -> AsyncIterator[str]:
    """Process a user message in a room and generate agentic responses."""
    await save_message(room_id, user_message, str(user_id), is_agent=False)

    messages = await get_room_messages(room_id, user_id)
    agents = await get_agents(user_id)
    agent_map = {a.id: a for a in agents}
    room_agents = await get_room_agents(room_id, user_id)

    if not room_agents:
        yield "No agents in this room to respond."
        return

    # Keep a running string of the history to pass to the orchestrator/agents
    history_lines = []
    for msg in messages:
        if msg.user_id:
            history_lines.append(f"User: {msg.content}")
        elif msg.agent_id:
            agent_name = agent_map[msg.agent_id].name if msg.agent_id in agent_map else "Agent"
            history_lines.append(f"{agent_name}: {msg.content}")

    # Memory context
    yield "[[STATUS:retrieving_memories]]\n"
    user_memories = await retrieve_memories(user_message, user_id=user_id)
    user_memory_block = ""
    if user_memories:
        joined = "\n- ".join(user_memories)
        user_memory_block = f"\n\nRelevant things I remember about the user:\n- {joined}\n"

    room_memories = await retrieve_memories(user_message, room_id=room_id)
    room_memory_block = ""
    if room_memories:
        joined = "\n- ".join(room_memories)
        room_memory_block = f"\n\nContext and past decisions from this room:\n- {joined}\n"

    turn_count = 0
    max_turns = 5  # Prevent infinite loops

    while turn_count < max_turns:
        history_text = "\n".join(
            history_lines[-10:]
        )  # Pass only recent history to keep context size manageable
        yield "[[STATUS:orchestrating]]\n"
        next_speakers = await orchestrate_turn(history_text, room_agents)

        if not next_speakers:
            break  # Orchestrator decided we are done for this turn

        for agent_id in next_speakers:
            if agent_id not in agent_map:
                continue

            agent = agent_map[agent_id]

            # Fetch persona memories specific to this agent
            yield f"[[STATUS:loading_agent:{agent.id}:{agent.name}]]\n"
            agent_memories = await retrieve_memories(user_message, agent_id=agent.id)
            agent_memory_block = ""
            if agent_memories:
                joined = "\n- ".join(agent_memories)
                agent_memory_block = f"\n\nYour past experiences/skills:\n- {joined}\n"

            yield f"[[AGENT:{agent.id}:{agent.name}]]\n"

            # Use the rich system prompt if available, otherwise fall back
            base_prompt = agent.system_prompt or (
                f"You are {agent.name}. Your personality is: {agent.personality}"
            )
            system_prompt = (
                f"{base_prompt}\n"
                f"You are in a group chat room. Respond naturally based on your personality "
                f"and the conversation context.{user_memory_block}{room_memory_block}{agent_memory_block}"
            )

            # Use CrewAI if the agent has capabilities that require tools
            has_web_search = "web_search" in agent.capabilities and get_settings().tavily_api_key

            agent_reply_chunks = []
            if has_web_search:
                yield f"[[STATUS:thinking_with_tools:{agent.name}]]\n"
                search_tool = TavilySearchTool(api_key=get_settings().tavily_api_key)

                crew_agent = CrewAgent(
                    role=agent.name,
                    goal=agent.description or f"Respond to the user as {agent.name}",
                    backstory=system_prompt,
                    llm=make_llm(),
                    tools=[search_tool],
                    verbose=False,
                )

                task = Task(
                    description=(
                        f"Conversation history:\n{history_text}\n\n"
                        f"It is your turn to speak. Please provide your response. "
                        "You can use the provided tools if needed to gather more information."
                    ),
                    expected_output="A natural, helpful response based on the agent's personality and the conversation history.",
                    agent=crew_agent,
                )

                crew = Crew(
                    agents=[crew_agent],
                    tasks=[task],
                    process=Process.sequential,
                    verbose=False,
                )

                loop = asyncio.get_event_loop()
                result = await loop.run_in_executor(None, crew.kickoff)
                full_reply = str(result)
                agent_reply_chunks.append(full_reply)
                yield full_reply
            else:
                llm_messages = [
                    {"role": "system", "content": system_prompt},
                    {
                        "role": "user",
                        "content": f"Conversation history:\n{history_text}\n\nIt is your turn to speak. Please provide your response.",
                    },
                ]

                async for chunk in stream_chat(llm_messages):
                    agent_reply_chunks.append(chunk)
                    yield chunk

            yield "\n\n"

            full_reply = "".join(agent_reply_chunks)
            await save_message(room_id, full_reply, agent.id, is_agent=True)

            # Update history for the next iteration / orchestrator check
            history_lines.append(f"{agent.name}: {full_reply}")

            # Extract memories asynchronously
            asyncio.create_task(
                store_memory(
                    user_message=history_text, assistant_reply=full_reply, agent_id=agent.id
                )
            )
            asyncio.create_task(
                store_memory(user_message=history_text, assistant_reply=full_reply, room_id=room_id)
            )

        turn_count += 1

    yield "[[STATUS:done]]\n"
