export const theme = {
  colors: {
    primary: {
      DEFAULT: '#2563EB',
      light: '#60A5FA',
      dark: '#1E40AF',
      surface: '#1E293B',
      surfaceLight: '#EFF6FF',
    },
    background: {
      dark: '#0F0F14',
      light: '#F8F8FC',
    },
    surface: {
      dark: '#1A1A22',
      highDark: '#242430',
      highestDark: '#2E2E3C',
      light: '#FFFFFF',
      highLight: '#F0F0F6',
      highestLight: '#E8E8F0',
    },
    border: {
      dark: '#3A3A4A',
      light: '#D8D8E4',
    },
    onSurface: {
      dark: '#F0EFF4',
      mutedDark: '#A0A0B0',
      disabledDark: '#606070',
      light: '#12121A',
      mutedLight: '#6E6E80',
      disabledLight: '#B0B0C0',
    },
    status: {
      success: '#34D399',
      successSurfaceDark: '#0D2E1F',
      successSurfaceLight: '#F0FDF4',
      warning: '#FBBF24',
      warningSurfaceDark: '#2E2610',
      warningSurfaceLight: '#FFFBEB',
      error: '#F87171',
      errorSurfaceDark: '#2E1212',
      errorSurfaceLight: '#FEF2F2',
      info: '#60A5FA',
      infoSurfaceDark: '#121E2E',
      infoSurfaceLight: '#EFF6FF',
    },
    transparent: 'transparent',
    white: '#FFFFFF',
    black: '#000000',
  },
  spacing: {
    none: 0,
    xxs: 2,
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 20,
    xxl: 24,
    xxxl: 32,
    huge: 40,
    massive: 48,
    colossal: 64,
    avatar: 28,
    bubbleIndent: 56,
    bubbleTimestampIndent: 36,
    bubblePaddingH: 14,
    bubblePaddingV: 10,
    inputBarButton: 44,
    inputBarStopSquare: 14,
    inputBarMinHeight: 44,
    inputBarMaxHeight: 130,
  },
  borderRadius: {
    none: 0,
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 20,
    xxl: 24,
    full: 9999,
  },
  typography: {
    h1: {
      fontSize: 32,
      fontWeight: 'bold' as const,
      lineHeight: 40,
      letterSpacing: -0.5,
    },
    h2: {
      fontSize: 24,
      fontWeight: '600' as const,
      lineHeight: 32,
      letterSpacing: -0.3,
    },
    h3: {
      fontSize: 20,
      fontWeight: '500' as const,
      lineHeight: 28,
      letterSpacing: -0.2,
    },
    body: {
      fontSize: 16,
      fontWeight: 'normal' as const,
      lineHeight: 24,
      letterSpacing: 0.1,
    },
    bodySm: {
      fontSize: 14,
      fontWeight: 'normal' as const,
      lineHeight: 20,
      letterSpacing: 0.1,
    },
    caption: {
      fontSize: 12,
      fontWeight: 'normal' as const,
      lineHeight: 16,
      letterSpacing: 0.2,
    },
  },
  elevation: {
    none: {
      shadowColor: 'transparent',
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0,
      shadowRadius: 0,
      elevation: 0,
    },
    sm: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.05,
      shadowRadius: 2,
      elevation: 1,
    },
    md: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    lg: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.15,
      shadowRadius: 8,
      elevation: 6,
    },
    xl: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.2,
      shadowRadius: 16,
      elevation: 12,
    },
  },
};
