import 'package:flutter/material.dart';

import 'api_service.dart';
import 'design_system/components/model_selector_sheet.dart';
import 'design_system/design_system.dart';

// ---------------------------------------------------------------------------
// Data models
// ---------------------------------------------------------------------------

/// A single message in the conversation.
class ChatMessage {
  final String text;
  final bool isUser;

  /// Set for assistant messages generated by a CrewAI crew.
  final String? crewTaskType;

  const ChatMessage({
    required this.text,
    required this.isUser,
    this.crewTaskType,
  });

  ChatMessage copyWith({String? text, String? crewTaskType}) => ChatMessage(
        text: text ?? this.text,
        isUser: isUser,
        crewTaskType: crewTaskType ?? this.crewTaskType,
      );
}

// ---------------------------------------------------------------------------
// Page
// ---------------------------------------------------------------------------

/// The main chat screen — the single page of the Miru app.
class ChatPage extends StatefulWidget {
  const ChatPage({super.key});

  @override
  State<ChatPage> createState() => _ChatPageState();
}

class _ChatPageState extends State<ChatPage> {
  final List<ChatMessage> _messages = [];
  final TextEditingController _inputController = TextEditingController();
  final ScrollController _scrollController = ScrollController();

  bool _isStreaming = false;

  /// Whether to route messages through the CrewAI multi-agent pipeline.
  bool _useCrew = false;

  /// Currently selected OpenRouter model ID. Null = server default.
  String? _selectedModel;

  // ---------------------------------------------------------------------------
  // Actions
  // ---------------------------------------------------------------------------

  void _scrollToBottom() {
    WidgetsBinding.instance.addPostFrameCallback((_) {
      if (_scrollController.hasClients) {
        _scrollController.animateTo(
          _scrollController.position.maxScrollExtent,
          duration: AppDurations.fast,
          curve: AppDurations.enterCurve,
        );
      }
    });
  }

  Future<void> _sendMessage() async {
    final text = _inputController.text.trim();
    if (text.isEmpty || _isStreaming) return;

    _inputController.clear();

    setState(() {
      _messages.add(ChatMessage(text: text, isUser: true));
      // Placeholder — empty text shows the typing indicator.
      _messages.add(const ChatMessage(text: '', isUser: false));
      _isStreaming = true;
    });
    _scrollToBottom();

    try {
      if (_useCrew) {
        await _sendCrewMessage(text);
      } else {
        await _sendStreamMessage(text);
      }
    } catch (e) {
      setState(() {
        final lastIndex = _messages.length - 1;
        _messages[lastIndex] = ChatMessage(text: 'Error: $e', isUser: false);
      });
    } finally {
      setState(() => _isStreaming = false);
    }
  }

  /// Streams a single-turn response token by token.
  Future<void> _sendStreamMessage(String text) async {
    await for (final chunk in ApiService.sendMessage(
      text,
      model: _selectedModel,
    )) {
      setState(() {
        final lastIndex = _messages.length - 1;
        _messages[lastIndex] = _messages[lastIndex].copyWith(
          text: _messages[lastIndex].text + chunk,
        );
      });
      _scrollToBottom();
    }
  }

  /// Sends a message through the CrewAI crew and waits for the full result.
  Future<void> _sendCrewMessage(String text) async {
    final result = await ApiService.runCrew(text, model: _selectedModel);
    setState(() {
      final lastIndex = _messages.length - 1;
      _messages[lastIndex] = ChatMessage(
        text: result.result,
        isUser: false,
        crewTaskType: result.taskType,
      );
    });
    _scrollToBottom();
  }

  void _openModelSheet() {
    showModalBottomSheet<void>(
      context: context,
      isScrollControlled: true,
      backgroundColor: Colors.transparent,
      builder: (_) => ModelSelectorSheet(
        currentModel: _selectedModel,
        onSelected: (id) => setState(() => _selectedModel = id),
      ),
    );
  }

  // ---------------------------------------------------------------------------
  // Build
  // ---------------------------------------------------------------------------

  @override
  Widget build(BuildContext context) {
    final colors = context.colors;

    return Scaffold(
      backgroundColor: colors.background,
      appBar: AppBar(
        backgroundColor: colors.surfaceHigh,
        centerTitle: true,
        title: Row(
          mainAxisSize: MainAxisSize.min,
          children: [
            const AppStatusDot.online(),
            const SizedBox(width: AppSpacing.sm),
            Text(
              'Miru',
              style: AppTypography.headingMedium.copyWith(
                color: colors.onSurface,
              ),
            ),
          ],
        ),
      ),
      body: Column(
        children: [
          // Message list
          Expanded(
            child: _messages.isEmpty
                ? const AppEmptyState(
                    icon: Icons.auto_awesome_rounded,
                    title: "Hi, I'm Miru.",
                    subtitle:
                        'I remember things about you over time.\nTell me something!',
                  )
                : ListView.builder(
                    controller: _scrollController,
                    padding: AppSpacing.chatListPadding,
                    itemCount: _messages.length,
                    itemBuilder: (context, index) {
                      final msg = _messages[index];
                      return ChatBubble(
                        text: msg.text,
                        isUser: msg.isUser,
                        crewTaskType: msg.crewTaskType,
                      );
                    },
                  ),
          ),

          // Input bar
          ChatInputBar(
            controller: _inputController,
            onSend: _sendMessage,
            isStreaming: _isStreaming,
            useCrew: _useCrew,
            onToggleCrew: (v) => setState(() => _useCrew = v),
            selectedModelName: _selectedModel,
            onSelectModel: _openModelSheet,
          ),
        ],
      ),
    );
  }

  @override
  void dispose() {
    _inputController.dispose();
    _scrollController.dispose();
    super.dispose();
  }
}
